version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src
      - /usr/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
