const images = [
	"/images/photos/face1.png",
	"/images/photos/face2.png",
	"/images/photos/face3.png",
	"/images/photos/face4.png",
	"/images/photos/face5.png",
	"/images/photos/face6.png",
	"/images/photos/face7.png",
	"/images/photos/face8.png",
	"/images/photos/face9.png",
	"/images/photos/face10.png",
	"/images/photos/face11.png",
	"/images/photos/face12.png",
	"/images/photos/face13.png",
	"/images/photos/face14.png",
	"/images/photos/face15.png",
	"/images/photos/face16.png",
	"/images/photos/full1.JPG",
	"/images/photos/full2.JPG",
	"/images/photos/full3.JPG",
	"/images/photos/full4.JPG",
	"/images/photos/full5.JPG",
	"/images/photos/full6.JPG",
];

export default images;
