import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RecoilRootProvider from "@/utils/recoilRootProvider";
import ScriptProvider from "@/utils/scriptProvider";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "BNK NO6.LEESOHEE",
	description: "Generated by hahanana20c",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Head>
				<ScriptProvider />
			</Head>
			<body className={inter.className}>
				<RecoilRootProvider>{children}</RecoilRootProvider>
			</body>
		</html>
	);
}
